# permissions for end users to view prints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: print-viewer-role
rules:
- apiGroups:
  - homework.podprinter.com
  resources:
  - prints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - homework.podprinter.com
  resources:
  - prints/status
  verbs:
  - get
