# permissions for end users to view podprinters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podprinter-viewer-role
rules:
- apiGroups:
  - homework.podprinter.com
  resources:
  - podprinters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - homework.podprinter.com
  resources:
  - podprinters/status
  verbs:
  - get
